---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Pull Image
      shell: docker pull ketakitam/calculator:latest

    - name: Run the container
      shell: docker run -it -d --name Calculator ketakitam/calculator